/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Lib.XDate;
import Lib.XFile;
import Model.MFQBYdate;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Trong The
 */
public class MFQBYAPP extends javax.swing.JFrame {
    DefaultTableModel TbModel; 
    DefaultComboBoxModel CbModel =new DefaultComboBoxModel();
    DefaultComboBoxModel CbModel2 =new DefaultComboBoxModel();
    String FilePath="";
    ArrayList<MFQBYdate> MFQBYList;
    int currentRow =-1;
    /**
     * Creates new form MFQBYAPP
     */
    public MFQBYAPP() {
        initComponents();
        initTable();
        loadCbRegions();
        loadCbFood();
        tbMFQBY.setDefaultEditor(Object.class, null);// chỉ chọn trên bản ko cho chĩnh sữa
        MFQBYList =new ArrayList<>();
        FilePath = "./src/Data/MFQBYdata.dat";
        boolean file = loadFile();
        if(file){
           fillToTable(); 
           
       }else{
            showmess("nothing to show");
        }
        this.setLocationRelativeTo(null);
      
        this.setTitle("Managet Food Quantity by Year app");
        
        //save and edit điều có 3 cái là lấy dữ liệu xuống, chỉnh sửa nó là save nó(up nó lên)
   
    }
    private void fillToTable(){
  TbModel.setRowCount (0);//lót bản
  for(MFQBYdate M: MFQBYList){
      Object[] row = new Object[]{M.getID(),M.getName()
              ,M.getQuantily(),M.getRegions(),M.getIAndE(),M.getTime()};
      TbModel.addRow(row);
  }
 }
 
 private void showmess(String mess){
  JOptionPane.showMessageDialog(this, mess);
 }
 
 private boolean loadFile(){
     
 if(XFile.readObject(FilePath)==null){
            showmess("nothing  to show");
            return false;
        }
        MFQBYList = (ArrayList<MFQBYdate>) XFile.readObject(FilePath);
        return true; 
 }
    private void loadCbRegions(){
     String[] RegionsLis = {"north","southern","central region" };
     for(String string:RegionsLis){
      CbModel.addElement(string); 
         
     }
     cbRegions.setModel(CbModel);
    }
    
    private void loadCbFood(){
     String[] RegionsLis = {"Chicken meat","Pork meat","Fish meat","Lamb meat"};
     for(String string:RegionsLis){
      CbModel2.addElement(string); 
         
     }
     cbFood.setModel(CbModel2);
    }
    
    
    private void initTable(){
    String[] columnNames = {"ID","Name Food","Quantily","Export Import","Regions","Time"};
        TbModel = new DefaultTableModel(columnNames,0);
        tbMFQBY.setModel(TbModel);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrExportImport = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtID = new javax.swing.JTextField();
        txtQuantily = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbRegions = new javax.swing.JComboBox<>();
        DateTime = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cbFood = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbMFQBY = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Manage Food Quantity By Year ");

        jLabel3.setText("ID");

        jLabel4.setText("Food");

        jLabel5.setText("Quantity (t)");

        jLabel6.setText("Import And Export");

        GrExportImport.add(jRadioButton1);
        jRadioButton1.setText("Import");
        jRadioButton1.setActionCommand("true");

        GrExportImport.add(jRadioButton2);
        jRadioButton2.setText("Export");
        jRadioButton2.setActionCommand("false");

        jLabel7.setText("Regions");

        cbRegions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DateTime.setDateFormatString("d/MM/y");

        jLabel8.setText("Time");

        cbFood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbRegions, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbFood, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtQuantily, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(90, 90, 90))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jRadioButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton1)
                            .addGap(47, 47, 47)))
                    .addComponent(DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbRegions, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Sort by ID");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Sort by Quantity");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        tbMFQBY.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMFQBY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbMFQBYMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbMFQBY);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addMFQBY();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbMFQBYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMFQBYMousePressed
        // TODO add your handling code here:
        currentRow = tbMFQBY.getSelectedRow();
        showDetail(currentRow);
        
    }//GEN-LAST:event_tbMFQBYMousePressed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Exit();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        updateCan();
        fillToTable();
        saveFile();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        deleteCan();
        fillToTable();
        saveFile();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        sortCanByQuantily();
        fillToTable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         SortCanByID();
        fillToTable();
    }//GEN-LAST:event_jButton4ActionPerformed
private void SortCanByID(){
    Collections.sort(MFQBYList,new Comparator<MFQBYdate>(){
        @Override
        public int compare(MFQBYdate o1, MFQBYdate o2) {
            return o1.getID().compareTo(o2.getID());//
        }
    
    });
}
    
private void sortCanByQuantily (){
Collections.sort(MFQBYList,new Comparator<MFQBYdate>(){

            @Override
            public int compare(MFQBYdate o1, MFQBYdate o2) {
               return o1.getQuantily()<o2.getQuantily()?-1:1;//
            }
        });
}
    
    
private void deleteCan(){
int result = JOptionPane.showConfirmDialog(this, "Do you want to delete this ?","delete",
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
if(result == JOptionPane.YES_OPTION){
MFQBYList.remove(currentRow);
resetform();
}
}
    
private void resetform(){
    cbRegions.setSelectedIndex(0);
    cbFood.setSelectedIndex(0);
}
    
    private void  updateCan(){
 MFQBYdate m= MFQBYList.get(currentRow);//
 m.setName(cbFood.getSelectedItem().toString());
 m.setQuantily(Double.parseDouble(txtQuantily.getText()));
 m.setIAndE(Boolean.parseBoolean(GrExportImport.getSelection().getActionCommand()));
 m.setRegions(cbRegions.getSelectedItem().toString());
}
    
    
private void Exit(){
int result = JOptionPane.showConfirmDialog(this, "Do you want to Exit this ?","Exit",
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
if(result == JOptionPane.YES_OPTION){
    System.exit(0);
}}
    
    
    private void showDetail(int r){
 String id = (String) tbMFQBY.getValueAt(r, 0);
   txtID.setText(id);
   
   String name = (String) tbMFQBY.getValueAt(r, 1);
   cbFood.setSelectedItem(name);
   
   Double quantily = (Double) tbMFQBY.getValueAt(r, 2);
   txtQuantily.setText(quantily.toString());
   
 MFQBYdate m = MFQBYList.get(r);
 
 String Regions = (String) tbMFQBY.getValueAt(r,3);
 cbRegions.setSelectedItem(Regions);
 
 
 Date birth = (Date) XDate.stringToDate(m.getTime());
 DateTime.setDate(birth);
 
 Boolean IAndE  = (Boolean) tbMFQBY.getValueAt(r, 4);
 setBtnGroup(IAndE.toString());
 }
 private void setBtnGroup(String value){ // kiem tra gia tri cha ve  
 for (Component c : jPanel2.getComponents()){
     
 if(c instanceof JRadioButton){
     
     JRadioButton btn = (JRadioButton) c;
     
     if(btn.getActionCommand().equals(value)){
         
      btn.setSelected(true);
     }
   }
 }
}
 
    
    private void addMFQBY(){
     String ID = txtID.getText();
     String name = cbFood.getSelectedItem().toString();
     Double quantily = Double.parseDouble(txtQuantily.getText());
     Boolean ExportImport = Boolean.parseBoolean(GrExportImport.getSelection().getActionCommand());
     String Regions = cbRegions.getSelectedItem().toString();
     
     Date birth = DateTime.getDate();
   String date = XDate.DateToString(birth);
   
   MFQBYdate m = new MFQBYdate(ID, name, quantily, ExportImport, Regions,date); 
   MFQBYList.add(m);
 }
  private void saveFile(){
      XFile.writeObject(FilePath, MFQBYList);
   }
 
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MFQBYAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MFQBYAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MFQBYAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MFQBYAPP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MFQBYAPP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateTime;
    private javax.swing.ButtonGroup GrExportImport;
    private javax.swing.JComboBox<String> cbFood;
    private javax.swing.JComboBox<String> cbRegions;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbMFQBY;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQuantily;
    // End of variables declaration//GEN-END:variables
}
